# Generated by Django 3.2.18 on 2023-02-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=15, unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('voice_file', models.FileField(upload_to='data')),
            ],
        ),
    ]
